# Generated by Django 4.2.7 on 2025-01-12 21:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0044_farmregistrygroup_farmregistry'),
        ('dcas', '0004_alter_dcasrequest_options_dcasoutput'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dcasoutput',
            options={'ordering': ['-delivered_at'], 'verbose_name': 'Output'},
        ),
        migrations.AlterModelOptions(
            name='dcasrequest',
            options={'ordering': ['-requested_at'], 'verbose_name': 'Request'},
        ),
        migrations.CreateModel(
            name='DCASErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_message', models.TextField(help_text='Details about why the farm could not be processed.')),
                ('logged_at', models.DateTimeField(default=django.utils.timezone.now, help_text='The time when the error was logged.')),
                ('farm_id', models.ForeignKey(help_text='The unique identifier of the farm that failed to process.', on_delete=django.db.models.deletion.CASCADE, to='gap.farm')),
                ('request', models.ForeignKey(help_text='The DCAS request associated with this error.', on_delete=django.db.models.deletion.CASCADE, related_name='error_logs', to='dcas.dcasrequest')),
            ],
            options={
                'verbose_name': 'Error Log',
                'db_table': 'dcas_error_log',
                'ordering': ['-logged_at'],
            },
        ),
    ]
